import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import Header from '@/components/header/header';
import Banner from '@/components/UI/banner/banner';
import Footer from '@/components/footer/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Flick Flow',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Banner />
        <main className="custom-grid max-w-[1780px] gap-[24px] m-auto min-h-screen py-8">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
