export const genres = [
  { input: 'checkbox', name: 'action', placeholder: 'Action' },
  {
    input: 'checkbox',
    name: 'action_adventure',
    placeholder: 'Action & Adventure',
  },
  { input: 'checkbox', name: 'adventure', placeholder: 'Adventure' },
  { input: 'checkbox', name: 'animation', placeholder: 'Animation' },
  { input: 'checkbox', name: 'biography', placeholder: 'Biography' },
  { input: 'checkbox', name: 'comedy', placeholder: 'Comedy' },
  { input: 'checkbox', name: 'crime', placeholder: 'Crime' },
  { input: 'checkbox', name: 'documentary', placeholder: 'Documentary' },
  { input: 'checkbox', name: 'drama', placeholder: 'Drama' },
  { input: 'checkbox', name: 'family', placeholder: 'Family' },
  { input: 'checkbox', name: 'fantasy', placeholder: 'Fantasy' },
  { input: 'checkbox', name: 'history', placeholder: 'History' },
  { input: 'checkbox', name: 'horror', placeholder: 'Horror' },
  { input: 'checkbox', name: 'kids', placeholder: 'Kids' },
  { input: 'checkbox', name: 'music', placeholder: 'Music' },
  { input: 'checkbox', name: 'mystery', placeholder: 'Mystery' },
  { input: 'checkbox', name: 'news', placeholder: 'News' },
  { input: 'checkbox', name: 'reality', placeholder: 'Reality' },
  { input: 'checkbox', name: 'romance', placeholder: 'Romance' },
  {
    input: 'checkbox',
    name: 'sci_fi_fantasy',
    placeholder: 'Sci-Fi & Fantasy',
  },
  {
    input: 'checkbox',
    name: 'science_fiction',
    placeholder: 'Science Fiction',
  },
  { input: 'checkbox', name: 'soap', placeholder: 'Soap' },
  { input: 'checkbox', name: 'talk', placeholder: 'Talk' },
  { input: 'checkbox', name: 'thriller', placeholder: 'Thriller' },
  { input: 'checkbox', name: 'tv_movie', placeholder: 'TV Movie' },
  { input: 'checkbox', name: 'war', placeholder: 'War' },
  { input: 'checkbox', name: 'war_politics', placeholder: 'War & Politics' },
  { input: 'checkbox', name: 'western', placeholder: 'Western' },
];
